use log::warn;

use super::{
  util::{self, ParseResult},
};

/// Ported from Fish's `TypeScdocManParser`
///
/// TODO This is completely untested
#[allow(clippy::case_sensitive_file_extension_comparisons)]
pub fn try_parse(cmd_name: &str, page_text: &str) -> Option<ParseResult> {
  if !page_text.starts_with(r#".\" Generated by scdoc"#) {
    None
  } else {
    Some(parse(cmd_name, page_text))
  }
}

fn parse(cmd_name: &str, page_text: &str) -> ParseResult {
  match util::get_section("OPTIONS", page_text) {
    Some(content) => {
      let mut flags = Vec::new();

      let mut paras = content.split(".PP");
      paras.next(); // Discard the part before the first option
      for para in paras {
        let data = util::remove_groff_formatting(para);
        let data = data.trim();
        if let Some((options, desc)) = data.split_once('\n') {
          if let Some(flag) = util::make_flag(options, Some(desc)) {
            flags.push(flag);
          }
        } else if !data.is_empty() {
          warn!(
            "In command {cmd_name}, no description, data: {}",
            util::truncate(data, 40)
          );
        }
      }

      Ok(flags)
    }
    None => Ok(vec![]),
  }
}
