THIS IS JUST FOR TESTING, NOT A REAL MAN PAGE

This corresponds to Fish's type 3 and is a subcommand of test1 sub1

test1 sub1 nested <- Need that for this to be picked up as a subcommand

.SH DESCRIPTION
-bleh bleh bleh
bleh bleh
.TP
\-co, \-\-command
Run a command or something
.HP
\-\-install
.IP
Install a thing
.SH Next section
