name: Lint

on:
  push:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clippy
        run: rustup component add clippy
      - name: Lint
        run: |
          cargo clippy -- \
            -Dwarnings \
            -Wclippy::all \
            -Wclippy::pedantic \
            -Aclippy::comparison_chain \
            -Aclippy::missing-panics-doc \
            -Aclippy::module-name-repetitions \
            -Aclippy::redundant-closure-for-method-calls
